# FONT.
TITLE_FONT = 'Rockwell'
VALUE_FONT = 'JetBrains Mono'

# DEFAULT VALUES.
DEFAULT_ROTATE = 0
DEFAULT_ZOOM = 0
FLIP_OPTIONS = ('NONE', 'X', 'Y', 'BOTH')
DEFAULT_BLUR = 0
DEFUALT_CONTRAST = 0
EFFECT_OPTIONS = ('NONE', 'EMBOSS', 'FIND EDGES', 'CONTOUR', 'EDGE ENHANCE')
DEFAULT_BRIGHTNESS = 1
DEFAULT_VIBRANCE = 1
DEFAULT_GRAYSCALE = False
DEFAULT_INVERT = False

# COLORS.
WHITE = '#FFF'
GREY = 'GREY'
BLUE = '#1F6AA5'
DARK_GREY = '#4A4A4A'
CLOSE_RED = '#8A0606'
SLIDER_BG = '#64686B'
CANVAS_BG = '#242424'
DROPDOWN_MAIN = '#444'
DROPDOWN_HOVER = '#333'
DROPDOWN_MENU = '#666'
