# TIME PERIOD.
TIME_OPTIONS = ['MAX', '1 YEAR', '6 MONTHS', 'MONTH', 'WEEK']

# COLORS.
BG_COLOR = '#19233C'
INPUT_BG_COLOR = '#121A2C'
TICK_COLOR = '#EEEEEE'
HIGHLIGHT_COLOR = '#21EAAD'
TEXT_COLOR = '#FFFFFF'
TITLE_HEX_COLOR = 0x003C2319
